#docker run --rm -it --name mygadget_cont -p 8010:8010
#-v /Users/valeriypilyaev/Desktop/Python_Pro/MyGadget/src:/my_gadget/src mygadget_image
#./commands/start_server_dev.sh

services:
  backend:
    build: ./
    container_name: mygadget_container
    working_dir: /my_gadget
    ports:
      - "8010:8000"
    command: sh ./commands/start_server_dev.sh
    volumes:
      - ./src:/my_gadget/src
      - ./commands:/my_gadget/commands
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo
  postgres:
    image: postgres:16.4
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  pg_data: { }
  mongo_data: { }
