#docker run --rm -it --name mygadget_cont -p 8010:8010
#-v /Users/valeriypilyaev/Desktop/Python_Pro/MyGadget/src:/my_gadget/src mygadget_image
#./commands/start_server_dev.sh

services:
  backend:
    build: ./
    container_name: mygadget_container
    working_dir: /mygadget
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    command: sh ./commands/start_server_${MODE}.sh
    volumes:
      - ./src:/mygadget/src
      - ./commands:/mygadget/commands
      - static_content:/mygadget/src/static
      - media_content:/mygadget/src/media
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:16.4
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  mongodb:
    image: mongo:6.0
    container_name: mongo_db_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    restart: on-failure

  mongoadmin:
    image: mongo-express
    restart: on-failure
    container_name: mongo_admin_container
    ports:
      - "8091:8081"
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/static:/src/static
      - ./src/media:/src/media
      - static_content:/mygadget/src/static
      - media_content:/mygadget/src/media
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  pg_data: {}
  mongo_data: {}
  static_content: {}
  media_content: {}
