# Generated by Django 4.2.15 on 2024-11-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mygadget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="mygadget.productcategory",
            ),
        ),
    ]
