name: Django CI

on:
  - push
  - pull_request

env:
  DJANGO_SETTINGS_MODULE: config.settings.dev

jobs:
  tests:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    services:
      postgres:
        image: postgres:16.4
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Docker on macOS
        run: |
          brew install --cask docker
          open --background -a Docker
          sleep 15

      - name: Verify Docker Installation
        run: docker --version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check migrations
        run: |
          python src/manage.py makemigrations
          python src/manage.py migrate
          python src/manage.py check

      - name: Run Tests
        run: |
          python src/manage.py test
          flake8 src --config=.flake8
